sirenmarkets/core

package.json, scripts/mainnet_create_markets.js, scripts/mainnet_market_setup_data.json, scripts/market_setup_data.json, scripts/transfer_ownership.js, subgraph/config/mainnet.json, subgraph/package.json
create a new truffle script for deploying and initializing the AMM's and 4 initial Markets on mainnet.
Note that once this merges, we can run the `mainnet_create_markets.js` script, but then we need to deploy the updated subgraph to mainnet, and then the deployer will need to create another PR  to update `marketsRegistryAddress` in `scripts/transfer_ownership.js` so that the transfer of ownership to the multisig address will work correctly
=> update deploy scripts to handle mainnet contract deployment

contracts/amm/IAddMarketToAmm.sol, contracts/amm/MinterAmm.sol, contracts/market/MarketsRegistry.sol, test/amm/minterAmmRemoveExpired.js
For deleting elements from storage we have two options
(i)   Remove(index) : Resets value at index to default value. Array size doesn't change. 
(ii)  Pop() : Removes the last element. Size reduces by 1
Option (i) This doesn't reduce size even after removal so doesn't change much from what is already there.
Option (ii)[implementation] : Here the order of elements will get changed. We can store the element at last index to expired index and pop the last element effectively deleting the expired element. But in few scenarios we might not be able to clear all expired markets. See below 2 scenarios
```
~ marked items are expired items
Scenario 1: All expired items are removed
~1      2        ~3        4    5  6   
6       2       ~3        4    5        
6       2        5        4 …
```
=> Feature minteramm openmarkets

contracts/amm/IAddMarketToAmm.sol, contracts/amm/MinterAmm.sol, contracts/market/MarketsRegistry.sol, scripts/create_markets.js, test/amm/minterAmmRemoveExpired.js
Prior to this commit we were not properly validating the caller on addMarket, and any address could pass any argument they wanted for 'sender' and add as many Markets as they wished.
Now we properly check that the calling contract is the MarketsRegistry.
=> use correct authentication for MinterAmm.addMarket.

contracts/amm/MinterAmm.sol, test/amm/minterAmmGuardPrice.ts
This PR should resolve an issue with deep in the money option pricing.
When a deep in the money option is priced the approximation logic can be over 100%. Other logic calling this assumes that pricing will be returned as a percentage (in base units where 100% = 10^18).
```
// value all active bTokens and wTokens at current prices
uint256 bPrice = getPriceForSeriesInternal(series, underlyingPrice);
// wPrice = 1 - bPrice
uint256 wPrice = uint256(1e18) - bPrice;
```
If the number is over 100% then we could cause transaction reverts.
This change adds a check in the calcPrice function to return 100% if the approximation goes over. Unit tests verify both put and call logic are guarded.
=> Guard pricing against invalid percentage in deep ITM options

subgraph/generated/AmmFactory/AmmFactory.ts, subgraph/generated/ERC1155Controller/ERC1155Controller.ts, subgraph/generated/ERC1155Controller/SeriesController.ts, subgraph/generated/ERC1155Controller/SimpleToken.ts, subgraph/generated/PriceOracle/PriceOracle.ts, subgraph/generated/SeriesController/SeriesController.ts, subgraph/generated/SeriesController/SimpleToken.ts, subgraph/generated/SeriesVault/SeriesVault.ts, subgraph/generated/schema.ts, subgraph/generated/templates/Amm/MinterAmm.ts, subgraph/generated/templates/Amm/SimpleToken.ts, subgraph/generated/templates/SimpleToken/SimpleToken.ts, subgraph/schema.graphql, subgraph/src/mappings/amm.ts
We want to be able to query for a particular account's trade events (BTokenBought, BTokenSold, and WTokenSold) for a particular Series. Prior to this commit there was no way to query by SeriesId. Now, a client can compare the BTokenBought and BTokenSold events to see when there are any instances where a user profited by buying low and selling high.
=> add seriesId field to AMM trade subgraph events.

contracts/amm/AmmDataProvider.sol, contracts/amm/IAmmDataProvider.sol, contracts/amm/MinterAmm.sol, scripts/lib/deploy_singleton_contracts.ts, test/amm/ammDataProviderUpdate.ts, test/util.ts
order to reduce the deployed bytecode size of the MinterAmm
getTotalPoolValue
getOptionTokensSaleValue
getCollateralValueOfAllExpiredOptionTokens
getRedeemableCollateral
This commit reduced the bytecode size by ~2400 bytes; from 24399 to 21982
This is backwards compatible because we keep all the existing
external/public MinterAmm functions the same, but their implementations
call out to the AmmDataProvider.
Finally, gas usage did not change noticeably except for the
withdrawCapital function.
=> Move the following 4 functions in MinterAmm over to AmmDataProvider in

subgraph/README.md, subgraph/generated/AmmFactory/AmmFactory.ts, subgraph/generated/schema.ts, subgraph/generated/templates/Amm/MinterAmm.ts, subgraph/schema.graphql, subgraph/src/mappings/amm.ts
This addresses issue #70 .
The changes here will add a new `transaction` field to the AMM events so we can show historical transaction activity against an AMM.
It looks like some of the generated files were out of date so they got picked up as well.
Added notes in the README for the subgraph about how to test locally with real data as well.
The main changes were done in `subgraph/schema.graphql`.  Most other files are auto generated.
=> Add transaction hash to the AMM events

contracts/series/PriceOracle.sol, test/seriesController/priceOracle.ts
Fixes issue #67 .
When adding a new token pair, the solidity code will now ensure it starts with a valid price.  If the oracle returns `0` it will revert the tx.
Unit test added to verify.
=> Ensure token pairs start with valid price

contracts/amm/SirenExchange.sol
Small change to fix compiler warnings found in SirenExchange.  Not required to be deployed but was just a clean up after auditing the code.
=> Fix compiler warnings

contracts/series/ISeriesController.sol, contracts/series/SeriesController.sol, contracts/series/SeriesControllerStorage.sol, hardhat.config.ts, package-lock.json, package.json, scripts/storage_layout.ts, test/amm/minterAmmRemoveExpired.ts, test/seriesController/cashSettlement.ts, test/seriesController/closeSeries.ts, test/seriesController/proxySeriesController.ts, test/seriesController/seriesExpirations.ts, test/util.ts
This PR adds the requirement that expiration dates must be explicitly added by the admin before they can be used in a series.  The owner account must add the list of expiration dates before "createSeries" can be called with that expiration.
* Each expiration that is added is given an ExpirationID which is the index into the list of expirations (starts with ID = 1)
* Expirations are added to a mapping so that a given expiration date can be used to look up the corresponding Expiration ID
* Expiration dates must be aligned to the 8 AM daily or weekly date
* Expirations can only be added in ascending order
Other changes
* Minimized the error messages to get the contract size below the limit
* Moved the contract variables out into a separate contract to ensure upgrade compatibility going …
=> Expiration Validation and Expiration IDs

contracts/amm/IMinterAmm.sol, contracts/amm/MinterAmm.sol, contracts/series/ISeriesController.sol, contracts/series/SeriesController.sol, contracts/series/SeriesControllerStorage.sol, contracts/series/SeriesDeployer.sol, test/amm/minterAmmRemoveExpired.ts, test/governance/governanceScenario.ts, test/seriesController/autoCreateSeries.ts, test/seriesController/proxySeriesController.ts, test/truffle-fixture.js, test/util.ts
* Allow SeriesController to manually create any strikes (owner only)
* Move strike range management into SeriesDeployer
* Use percentages of the underlying price for strike range
* Allow SeriesDeployer to be upgradable
This will allow the series management logic to be expanded in the future without reaching the limit of SeriesController code size
=> Refactor strikes management into SeriesDeployer

contracts/amm/MinterAmm.sol, contracts/configuration/AddressesProvider.sol, contracts/configuration/IAddressesProvider.sol, test/amm/minterAmmDirectBuy.ts
Currently executing a direct buy order requires owner multisig signature. This enables setting a separate address to manage execution of direct buy orders.
=> Configure direct buy manager

contracts/series/SeriesDeployer.sol, test/seriesController/autoCreateSeries.ts
Limit the number of series that can be created per expiration to 15
=> Limit number of series per expiration

contracts/configuration/AddressesProvider.sol, contracts/configuration/IAddressesProvider.sol, contracts/series/SeriesDeployer.sol, test/configuration/addresssesProvider.ts, test/util.ts
`SeriesController` is tightly coupled with `ERC1155Controller`. As such it should always be retrieved as `seriesController.erc1155Controller()` instead of via the addresses provider.
=> Removed ERC1155Controller from AddressesProvider

contracts/amm/IWTokenVault.sol, contracts/amm/MinterAmm.sol, contracts/amm/WTokenVault.sol, contracts/test/MockVolatilityOracle.sol, test/amm/wTokenVault.ts, test/oracles/volatilityOracle.ts
Split locked wTokens by expiration to prevent LPs from having access to cash outside of the expirations they have locked wTokens for. Before this fix LPs had access to cashflows in perpetuity, which is a bug.
=> Bucket locked wTokens by expiration

contracts/amm/AmmFactory.sol, contracts/configuration/AddressesProvider.sol, contracts/series/SeriesController.sol, contracts/series/SeriesDeployer.sol, contracts/series/SeriesVault.sol, scripts/lib/deploy_singleton_contracts.ts, test/amm/minterAmmUpgradeable.ts, test/configuration/addresssesProvider.ts, test/seriesController/proxySeriesController.ts, test/seriesVault/proxySeriesVault.ts, test/util.ts
We decided to revert this change. The reason is that using `initialize` instead of a unique contract-specific name creates a risk of colliding with `initialize` method on inherited contract, for example this happens with the ERC1155 contract.
=> Revert 5.7 changes

contracts/series/IPriceOracle.sol, contracts/series/PriceOracle.sol, contracts/test/MockPriceOracle.sol, test/amm/minterAmmExpired.ts, test/amm/minterAmmGas.ts, test/amm/wTokenVault.ts, test/chainlink-keepers/priceOracleKeeper.ts, test/oracles/priceOracle.ts, test/seriesController/cashSettlement.ts, test/seriesController/seriesScenarios.ts, test/util.ts
Previously the settlement oracle used the latest chainlink price as settlement price. This made the settlement price sensitive to how soon the `setSettlementPrice` transaction is mined. This PR makes it search for the earliest oracle round after the settlement date instead.
=> Find earliest round for settlement price

contracts/amm/AmmDataProvider.sol, contracts/amm/IAmmDataProvider.sol, contracts/amm/MinterAmm.sol, contracts/amm/WTokenVault.sol, contracts/series/ISeriesController.sol, contracts/series/SeriesController.sol, test/amm/minterAmmPut.ts, test/amm/pricing.ts, test/seriesController/closeSeries.ts, test/seriesController/seriesScenarios.ts
Current implementation only provides methods to get pricing for series that already exist in the system (`AmmDataProvider.getPriceForSeries`, `AmmDataProvider.bTokenGetCollateralInView`). In order to complete the auto-series-creation project we need versions of these methods that instead of `seriesId` take `ISeriesController.Series` object. These 2 methods will allow the front-end code to calculate pricing for nonexistent series.
=> pricing for non existent series

contracts/amm/AmmDataProvider.sol, contracts/amm/IAmmDataProvider.sol, contracts/amm/MinterAmm.sol, contracts/amm/WTokenVault.sol, contracts/series/ISeriesController.sol, contracts/series/SeriesController.sol, test/amm/minterAmmPut.ts, test/amm/pricing.ts, test/seriesController/closeSeries.ts, test/seriesController/seriesScenarios.ts
I'm reverting this. It was merged prematurely. One issue is the change from using `getPriceForSeriesInternal` to `getPriceForSeries` in the `getTotalPoolValue`, which results in the underlying price being repeatedly requested for each series. After this revert is merged @lukaskiss222 could you create a PR again with you changes and let's not merge it until I approve as well.
=> Revert "pricing for non existent series"

contracts/series/SeriesDeployer.sol, test/seriesController/autoCreateSeries.ts
I changed the approval from msg.sender to address(this) because we should be giving approval to the deployer contract not to the sender because we need to send reaming tokens back to the user from the deployer.
=> Fixed approval for series deployer
